import { ExtensionContainer, ExtensionStage } from 'tessa/extensions';
import { PnrActUIExtension } from './PnrActUIExtension';
import { PnrContractUIExtension } from './PnrContractUIExtension';
import { PnrErrandUIExtension } from './PnrErrandUIExtension';
import { PnrIncomingUIExtension } from './PnrIncomingUIExtension';
import { PnrOrderUIExtension } from './PnrOrderUIExtension';
import { PnrOutgoingUIExtension } from './PnrOutgoingUIExtension';
import { PnrPartnerRequestUIExtension } from './PnrPartnerRequestUIExtension';
import { PnrPartnerUIExtension } from './PnrPartnerUIExtension';
import { PnrPowerAttorneyUIExtension } from './PnrPowerAttorneyUIExtension';
import { PnrRegulationUIExtension } from './PnrRegulationUIExtension';
import { PnrServiceNoteUIExtension } from './PnrServiceNoteUIExtension';
import { PnrSuppAgrUIExtension } from './PnrSuppAgrUIExtension';
import { PnrUKContractUIExtension } from './PnrUKContractUIExtension';
import { PnrUKIncomingUIExtension } from './PnrUKIncomingUIExtension';
import { PnrUKOrderUIExtension } from './PnrUKOrderUIExtension';
import { PnrUKOutgoingUIExtension } from './PnrUKOutgoingUIExtension';
import { PnrUKSuppAgrUIExtension } from './PnrUKSuppAgrUIExtension';
import { PnrHierarchyMenuTilesExtension } from './PnrHierarchyMenuTilesExtension';
import { PnrMetadataInitalizationExtension, PnrMetadataContainer, PnrMetadataContainerClerk, PnrMetadataContainerOfficeManager } from './PnrMetadataExtension';

ExtensionContainer.instance.registerExtension({extension: PnrActUIExtension, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrContractUIExtension, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrErrandUIExtension, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrIncomingUIExtension, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrOrderUIExtension, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrOutgoingUIExtension, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrPartnerRequestUIExtension, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrPartnerUIExtension, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrPowerAttorneyUIExtension, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrRegulationUIExtension, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrServiceNoteUIExtension, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrSuppAgrUIExtension, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrUKContractUIExtension, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrUKIncomingUIExtension, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrUKOrderUIExtension, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrUKOutgoingUIExtension, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrUKSuppAgrUIExtension, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrHierarchyMenuTilesExtension, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrMetadataContainer, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrMetadataContainerClerk, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrMetadataContainerOfficeManager, stage: ExtensionStage.AfterPlatform});
ExtensionContainer.instance.registerExtension({extension: PnrMetadataInitalizationExtension, stage: ExtensionStage.AfterPlatform});
